[package]
name = "edamame_posture"
version = "0.3.34"
edition = "2021"

[lib]
# Dynamic lib version is not used on apple platforms as it's painful but we must use it on windows and linux
# We must keep "lib" if we want to build targets with cargo
crate-type = ["staticlib", "lib"]

[dependencies]

# EDAMAME foundation
# TODO: don't depend on local path - required for the macOS build process for now
#edamame_foundation = { git = "https://github.com/edamametechnologies/edamame_foundation" }
edamame_foundation = { path = "../edamame_foundation" }
edamame_core = { path = "../edamame_core" }

# YAML
serde = "1.0.204"
serde_yaml = "0.9.34+deprecated"

# System
sysinfo = "0.30.13"
dirs = "5.0.1"

# CLI
clap = "4.1.1"

# Logging
tracing = "0.1.40"

# Sentry
sentry = "0.34.0"

[build-dependencies]

# Environment variables (build time)
dotenv-build = "0.1"

# Build metadata
vergen = { version = "8.3.1", features = ["build", "git", "gitcl", "si"] }