[package]
name = "edamame_posture"
version = "0.3.83"
edition = "2021"

[dependencies]

# EDAMAME foundation
edamame_foundation = { git = "https://github.com/edamametechnologies/edamame_foundation", branch = "dev" }
edamame_core = { git = "https://github.com/edamametechnologies/edamame_core", branch = "dev", features = [ "nohealth", "nolanscan", "nopwned", "nobridge", "swiftrs" ] }

# YAML
serde = "1.0.204"
serde_yaml = "0.9.34+deprecated"

# System
sysinfo = "0.30.13"
dirs = "5.0.1"

# CLI
clap = "4.1.1"

# Logging
tracing = "0.1.40"

# Sentry
sentry = "0.34.0"

# Encrypted env (weak)
envcrypt = "0.5.0"

# Process
[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
daemonize = "0.5.0"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser", "winbase", "handleapi", "processthreadsapi", "synchapi"] }
widestring = "1.1.0"

[build-dependencies]

# Build metadata
vergen = { version = "8.3.1", features = ["build", "git", "gitcl", "si"] }

