[package]
name = "edamame_posture"
version = "0.3.82"
edition = "2021"

[dependencies]

# EDAMAME foundation
edamame_foundation = { git = "https://github.com/edamametechnologies/edamame_foundation", branch = "dev" }
edamame_core = { git = "https://github.com/edamametechnologies/edamame_core", branch = "dev" }

# YAML
serde = "1.0.204"
serde_yaml = "0.9.34+deprecated"

# System
sysinfo = "0.30.13"
dirs = "5.0.1"

# CLI
clap = "4.1.1"

# Logging
tracing = "0.1.40"

# Sentry
sentry = "0.34.0"

[build-dependencies]

# Environment variables (build time)
dotenv-build = "0.1"

# Build metadata
vergen = { version = "8.3.1", features = ["build", "git", "gitcl", "si"] }

