[package]
name = "edamame_posture"
version = "0.3.34"
edition = "2021"

[[bin]]
name = "edamame_posture"
path = "src/lib.rs"

[dependencies]

# EDAMAME foundation
# TODO: don't depend on local path - required for the macOS build process for now
#edamame_foundation = { git = "https://github.com/edamametechnologies/edamame_foundation" }
edamame_foundation = { path = "../edamame_foundation" }
edamame_core = { path = "../edamame_core" }


# CLI
clap = "4.1.1"

# Logging
log = "0.4"

# Sentry
sentry = "0.32.1"

[build-dependencies]

# Environment variables (build time)
dotenv-build = "0.1"

# Build metadata
vergen = { version = "8.3.1", features = ["build", "git", "gitcl", "si"] }